##
# Configure my prompts and things, for Onebox 20.
#

---
- name: Onebox 20
  hosts: localhost
  gather_facts: False
  user: root

  tasks:
    - name: For root's home directory
      action: copy src=files/root-bash_custom dest=/root/.bash_custom owner=root group=root
      tags: prompt

    ##
    # Now the bash general stuff.
    #
    - include: ../lib/bash/bash.yml tags=bash

    ##
    # Git config.
    #
    - include: ../lib/git/git.yml tags=git

    ##
    # Utility link
    #
    - name: Link to systemd
      file: src=/etc/systemd/system dest=/root/sd owner=root group=root state=link
