##
# Configure my prompts and things
#

---
- hosts: all
  user: root

  tasks:
    ##
    # Prompts: Move files into place and configure
    #
    - include: ../lib/prompts/prompts.yml

    - name: For mark's home directory
      action: copy src=files/mark-bashrc dest=/home/mark/.bashrc owner=mark group=mark

    - name: For root's home directory
      action: copy src=files/root-bashrc dest=/root/.bashrc owner=root group=root

    ##
    # Now the bash general stuff.
    #
    - include: ../lib/bash/bash.yml

    - name: Bashrc
      action: copy src=files/etc-bashrc dest=/etc/bashrc

    ##
    # Mac mounts.
    #
    - include: ../lib/mounts/mounts.yml

    ##
    # Git config
    #
    - name: For mark's home directory
      action: copy src=../lib/git/gitconfig dest=/home/mark/.gitconfig owner=mark group=mark

    - name: For root's home directory
      action: copy src=../lib/git/gitconfig dest=/root/.gitconfig owner=root group=root

    ##
    # To get 'ls' to show hidden files first, this is required.
    #
    - name: Make ls show hidden files and dirs first.
      action: copy src=files/etc-sysconfig-i18n dest=/etc/sysconfig/i18n
