##
# Configure my prompts and things
#

---
- hosts: all
  user: root

  tasks:
    ##
    # Prompts: Move files into place and configure
    #
    - include: ../prompts/prompts.yml

    - name: For mark's home directory
      action: copy src=files/mark-bashrc dest=/home/mark/.bashrc owner=mark group=mark

    - name: For root's home directory
      action: copy src=files/root-bashrc dest=/root/.bashrc owner=root group=root

    ##
    # Now the bash general stuff.
    #
    - name: Create directory
      action: file path=/opt/bash state=directory

    - name: Functions
      action: copy src=../bash/functions dest=/opt/bash/functions

    - name: Aliases
      action: copy src=../bash/aliases dest=/opt/bash/aliases

    - name: Variables
      action: copy src=../bash/variables dest=/opt/bash/variables

    - name: Bashrc
      action: copy src=files/etc-bashrc dest=/etc/bashrc

    ##
    # To get 'ls' to show hidden files first, this is required.
    #
    - name: Make ls show hidden files and dirs first.
      action: copy src=files/etc-sysconfig-i18n dest=/etc/sysconfig/i18n
