##
# Configure my prompts and things, for Fedora 17.
#

---
- name: Fedora 17
  hosts: all
  gather_facts: False
  user: root

  tasks:
    ##
    # SSH Keys.
    #
    - include: ../lib/ssh/keys.yml tags=ssh

    ##
    # Prompts: Move files into place and configure.
    #
    - include: ../lib/prompts/prompts.yml tags=prompt

    - name: For mark's home directory
      action: copy src=files/mark-bashrc dest=/home/mark/.bashrc owner=mark group=mark
      tags: prompt

    - name: For root's home directory
      action: copy src=files/root-bashrc dest=/root/.bashrc owner=root group=root
      tags: prompt

    ##
    # Now the bash general stuff.
    #
    - include: ../lib/bash/bash.yml tags=bash

    - name: Bashrc
      action: copy src=files/etc-bashrc dest=/etc/bashrc
      tags: bash

    ##
    # Mac host mounts over NFS. Use systemd to automount them on first access,
    # using noauto,comment=systemd.automount
    #
    - include: ../lib/mounts/mounts.yml tags=mount

    - name: Mount Dropbox
      action: mount name=/home/mark/Dropbox src=machost:/Users/mark/Dropbox fstype=nfs opts=rw,suid,exec,noauto,sync,soft,timeo=20,comment=systemd.automount dump=0 passno=0 state=mounted
      tags: mount

    - name: Mount Workarea
      action: mount name=/home/mark/Workarea src=machost:/Users/mark/Workarea fstype=nfs opts=rw,suid,exec,noauto,sync,soft,timeo=20,comment=systemd.automount dump=0 passno=0 state=mounted
      tags: mount

    - name: Mount Sites
      action: mount name=/home/mark/Sites src=machost:/Users/mark/Sites fstype=nfs opts=rw,suid,exec,noauto,sync,soft,timeo=20,comment=systemd.automount dump=0 passno=0 state=mounted
      tags: mount

    ##
    # Git config.
    #
    - include: ../lib/git/git.yml tags=git

    ##
    # To get 'ls' to show hidden files first.
    #
    - name: Make ls show hidden files and dirs first.
      action: copy src=files/etc-sysconfig-i18n dest=/etc/sysconfig/i18n
      tags: general
